name: Haxe

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    strategy:
      matrix:
        haxe-version: ["4.2.5"]
        target: [cpp]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Install Haxe
      - run: sudo apt-get update
      - run: sudo apt install haxe
      - name: Setup Haxelib
      - run: haxelib setup ~/haxelib
      # - run: haxelib install <all dependencies>
      - name: Build
      - run: haxe build.hxml
