name: HaxeCI

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    strategy:
      matrix:
        haxe-version: ["4.2.5"]
        target: [cpp]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update
    - uses: actions/checkout@v2
    - run: haxelib setup ~/haxelib
    - run: haxe build.hxml
      with:
        haxe-version: ${{matrix.haxe-version}}
        test-location: local
        target: ${{matrix.target}}
        run-tests: true
